#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get install haproxy=2.0.\*
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\n\tdefault_backend web-backend" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
echo -e "\nbackend web-backend\n\tbalance roundrobin\n\tserver 6874-web-01 3.229.142.17:80 check\n\tserver 6874-web-02 3.237.21.165:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
sudo service haproxy restart
