#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer 
sudo apt-get -y update
sudo apt-get install haproxy
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\n\tdefault_backend web-backend" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\nbackend web-backend\n\tbalance roundrobin\n\tserver 6874-web-01 3.229.142.17:80 check\n\tserver 6874-web-02 3.237.21.165:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
