#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer 
sudo apt-get -y update
sudo apt-get install haproxy
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\n\tdefault_backend web-backend" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\nbackend web-backend\n\tbalance roundrobin\n\tserver web-01 web-01.emperorsword.tech.com:80 check\n\tserver web-02 web-02.emperorsword.tech:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
