#!/usr/bin/env bash
#this script displays specified text
#for multiples of 3 and 5 in between the numbers 1-100
i=1
three=3
five=5
while [ $i -le 100 ]
do
	mul3=$(( i % three ))
	mul5=$(( i % five ))
	if [ $mul3 = "0" ] && [ $mul5 = "0" ];
	then
		echo "FizzBuzz"
	elif [ $mul3 = "0" ];
	then
		echo "Fizz"
	elif [ $mul5 = "0" ];
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	((i++))
done
