#!/usr/bin/env bash
#prints directory contents starting from dash
touch contents
ls >> contents
for i in $(cat contents)
do
	print=1
        echo "$i" > temp_file
	bytes=$(wc -m temp_file | cut -b 1-2)
        for ((j=1; j<bytes; j++))
        do
		b=$(cut -b $j temp_file)
                if [ "$b" = "-" ]
                then
			if [ "$print" = "1" ]
			then
				((j++))
                        	cut -b $j- temp_file
				((j--))
				print=0
			fi
                fi
        done;
done
rm temp_file
rm contents
