#!/usr/bin/env bash
#prints directory contents starting from dash
touch contents
ls >> contents
for i in $(cat contents)
do
        echo "$i" > temp_file
	bytes=$(wc -m temp_file | cut -b 1-2)
        for ((j=1; j<bytes; j++))
        do
		b=$(cut -b $j temp_file)
                if [ "$b" = "-" ]
                then
			((j++))
                        cut -b $j- temp_file
			((j--))
                fi
        done;
done
rm temp_file
rm contents
